[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Team_Generic_SPIDAM"
version = "0.0.1"
authors = [
  { name="Robert Baumgarten", email="rbaumgarten3422@floridapoly.edu" },
  { name="Cody Taylor", email="ctaylor3707@floridapoly.edu" }
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/rbaumgarten1119/Team_Generic_SPIDAM"
Issues = "https://github.com/rbaumgarten1119/Team_Generic_SPIDAM/issues"